### PR TITLE
There is an syntax error fixed

### PR DESCRIPTION
**Pull request by onlyangel**
There is a simple syntax error. I think this fix it. And don't mess with the functionality.

### CODE REVIEW

**Comment by dsymonds** [comment]
The Go project doesn't use GitHub pull requests. We use Gerrit for code review. See https://golang.org/doc/contribute.html.

Please re-send this using Gerrit. Thanks!

**Comment by dsymonds** [comment]
But also, that's not a syntax error.

**Comment by onlyangel** [comment]
But i keep getting this:

```
The Go application could not be built.

/root/appscale/AppServer/goroot/src/pkg/golang.org/x/text/transform/transform.go:520: syntax error: unexpected :, expecting ]
```

**Comment by dsymonds** [comment]
You probably have an old version of Go. That syntax was added in Go 1.2, which was released back in December 2013.

**Comment by onlyangel** [comment]
Thanks for the advice. Now I need to find a way to keep in go1.1.2

**Pull request closed without merging**
